# Generated by Django 4.1.7 on 2023-04-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='redactor',
            options={'ordering': ['username'], 'verbose_name': 'redactor', 'verbose_name_plural': 'redactors'},
        ),
    ]
